import type {
  AssistantMessage,
  DemoActivity,
  DemoCase,
  EvidenceReference,
  HypothesisColumn,
  HypothesisRow,
} from "./types";

export const demoCases: DemoCase[] = [
  {
    id: "case-104",
    reference: "CASE-104",
    title: "Forgotten Fund Relay",
    category: "Financial fraud",
    description: "Synthetic review of a coordinated account, device, and communication trail reported across three complaints.",
    status: "ACTIVE",
    priority: "CRITICAL",
    owner: "A. Mehra",
    createdAt: "2026-08-08T09:20:00+05:30",
    updatedAt: "2026-08-30T17:45:00+05:30",
    entityCount: 42,
    evidenceCount: 18,
  },
  {
    id: "case-087",
    reference: "CASE-087",
    title: "Digital Extension Desk",
    category: "Cyber extortion",
    description: "Synthetic communications and wallet-transfer review associated with a staged extortion report.",
    status: "ACTIVE",
    priority: "HIGH",
    owner: "N. Roy",
    createdAt: "2026-08-11T11:05:00+05:30",
    updatedAt: "2026-08-29T14:11:00+05:30",
    entityCount: 28,
    evidenceCount: 12,
  },
  {
    id: "case-311",
    reference: "CASE-311",
    title: "Investment Signal Mosaic",
    category: "Investment fraud",
    description: "Synthetic analysis of recurring account references in an investment solicitation pattern.",
    status: "REVIEW",
    priority: "HIGH",
    owner: "S. Iyer",
    createdAt: "2026-08-14T15:30:00+05:30",
    updatedAt: "2026-08-28T10:22:00+05:30",
    entityCount: 31,
    evidenceCount: 10,
  },
  {
    id: "case-412",
    reference: "CASE-412",
    title: "Phishing Ring - East Zone",
    category: "Phishing",
    description: "Synthetic review of shared device artifacts and incoming call patterns.",
    status: "ACTIVE",
    priority: "MEDIUM",
    owner: "R. Das",
    createdAt: "2026-08-16T13:05:00+05:30",
    updatedAt: "2026-08-27T18:40:00+05:30",
    entityCount: 19,
    evidenceCount: 8,
  },
  {
    id: "case-508",
    reference: "CASE-508",
    title: "UPI Trail - Lakeview",
    category: "Payment fraud",
    description: "Synthetic payment-node triage awaiting corroborating source records.",
    status: "ARCHIVED",
    priority: "LOW",
    owner: "M. Sen",
    createdAt: "2026-08-03T09:10:00+05:30",
    updatedAt: "2026-08-23T16:10:00+05:30",
    entityCount: 14,
    evidenceCount: 6,
  },
];

export const demoEvidence: EvidenceReference[] = [
  {
    id: "E-102",
    caseId: "case-104",
    documentRef: "CDR-104-07",
    title: "Call detail extract - handset ending 4421",
    source: "Synthetic telecom record",
    kind: "CALL_DETAIL",
    status: "VERIFIED",
    confidence: 0.96,
    timestamp: "2026-08-12T18:42:00+05:30",
    excerpt: "A short outbound contact connects the handset record to the recovered device identifier.",
    entityIds: ["person-rahul", "phone-4421", "device-90a"],
  },
  {
    id: "E-117",
    caseId: "case-104",
    documentRef: "BNK-104-11",
    title: "Account movement summary",
    source: "Synthetic bank record",
    kind: "BANK_RECORD",
    status: "VERIFIED",
    confidence: 0.93,
    timestamp: "2026-08-13T09:15:00+05:30",
    excerpt: "Two staged transfers converge on a shared account reference within the reviewed period.",
    entityIds: ["bank-2290", "bank-7744", "person-rahul"],
  },
  {
    id: "E-121",
    caseId: "case-104",
    documentRef: "WIT-104-03",
    title: "Park Street observation note",
    source: "Synthetic witness note",
    kind: "WITNESS_NOTE",
    status: "INFERRED",
    confidence: 0.71,
    timestamp: "2026-08-12T19:10:00+05:30",
    excerpt: "The note describes a meeting point and should be corroborated before it is treated as fact.",
    entityIds: ["person-rahul", "location-park-street"],
  },
  {
    id: "E-134",
    caseId: "case-104",
    documentRef: "DEV-104-19",
    title: "Recovered device activity log",
    source: "Synthetic device log",
    kind: "DEVICE_LOG",
    status: "VERIFIED",
    confidence: 0.89,
    timestamp: "2026-08-14T11:25:00+05:30",
    excerpt: "A device fingerprint is observed in the same synthetic evidence bundle as the account alert.",
    entityIds: ["device-90a", "bank-2290"],
  },
  {
    id: "E-203",
    caseId: "case-087",
    documentRef: "DOC-087-04",
    title: "Recovered message export",
    source: "Synthetic document",
    kind: "DOCUMENT",
    status: "VERIFIED",
    confidence: 0.91,
    timestamp: "2026-08-19T14:03:00+05:30",
    excerpt: "The export contains a shared wallet label, but not a conclusion about ownership.",
    entityIds: ["phone-4421", "bank-7744"],
  },
  {
    id: "E-301",
    caseId: "case-311",
    documentRef: "CCTV-311-02",
    title: "Entry-point observation",
    source: "Synthetic CCTV note",
    kind: "CCTV_NOTE",
    status: "HYPOTHESIS",
    confidence: 0.54,
    timestamp: "2026-08-21T10:35:00+05:30",
    excerpt: "The observation is an analytical lead and must not be presented as an identity determination.",
    entityIds: ["person-rahul", "location-park-street"],
  },
];

export const demoActivities: DemoActivity[] = [
  {
    id: "A-001",
    caseId: "case-104",
    timestamp: "2026-08-30T17:45:00+05:30",
    title: "Relationship reviewed",
    description: "A device-to-account link was marked for investigator review with its source records retained.",
    category: "ANALYSIS",
    entityIds: ["device-90a", "bank-2290"],
    evidenceId: "E-134",
  },
  {
    id: "A-002",
    caseId: "case-104",
    timestamp: "2026-08-14T11:25:00+05:30",
    title: "Device log ingested",
    description: "A synthetic device log was indexed and associated with the active case context.",
    category: "EVIDENCE",
    entityIds: ["device-90a"],
    evidenceId: "E-134",
  },
  {
    id: "A-003",
    caseId: "case-104",
    timestamp: "2026-08-13T09:15:00+05:30",
    title: "Account transfer sequence added",
    description: "Two record-backed transaction references were added to the evidence graph.",
    category: "NETWORK",
    entityIds: ["bank-2290", "bank-7744"],
    evidenceId: "E-117",
  },
  {
    id: "A-004",
    caseId: "case-104",
    timestamp: "2026-08-12T19:10:00+05:30",
    title: "Observation note queued",
    description: "A contextual note was recorded as inference pending source verification.",
    category: "EVIDENCE",
    entityIds: ["person-rahul", "location-park-street"],
    evidenceId: "E-121",
  },
  {
    id: "A-005",
    caseId: "case-087",
    timestamp: "2026-08-19T14:03:00+05:30",
    title: "Message export linked",
    description: "A shared identifier was attached to a second synthetic case for review.",
    category: "CASE",
    entityIds: ["phone-4421", "bank-7744"],
    evidenceId: "E-203",
  },
];

export const hypothesisColumns: HypothesisColumn[] = [
  { id: "H1", shortLabel: "H1", title: "Single coordinated relay", qualifier: "Tests whether the observed links form one synthetic relay." },
  { id: "H2", shortLabel: "H2", title: "Shared intermediary", qualifier: "Tests whether an intermediary explains the overlapping records." },
  { id: "H3", shortLabel: "H3", title: "Coincidental overlap", qualifier: "Tests whether the available records are insufficient to link contexts." },
];

export const hypothesisRows: HypothesisRow[] = [
  {
    id: "HR-01",
    evidenceId: "E-102",
    reference: "CDR-104-07",
    evidence: "Handset contact and recovered-device reference occur in the same reviewed window.",
    cells: {
      H1: { verdict: "supports", rationale: "The verified record is consistent with a coordination path, but it does not establish intent or identity." },
      H2: { verdict: "supports", rationale: "The record could also be explained by a shared intermediary or service point." },
      H3: { verdict: "unknown", rationale: "This single record does not resolve whether the overlap is meaningful or coincidental." },
    },
  },
  {
    id: "HR-02",
    evidenceId: "E-117",
    reference: "BNK-104-11",
    evidence: "Two staged transfer references converge on a shared account identifier.",
    cells: {
      H1: { verdict: "supports", rationale: "The movement pattern is compatible with a coordinated relay in this synthetic scenario." },
      H2: { verdict: "supports", rationale: "A shared account could operate as an intermediary; ownership remains unverified." },
      H3: { verdict: "contradicts", rationale: "The repeated convergence makes a purely coincidental overlap less consistent with the present records." },
    },
  },
  {
    id: "HR-03",
    evidenceId: "E-121",
    reference: "WIT-104-03",
    evidence: "An observation note places a named person near the listed location.",
    cells: {
      H1: { verdict: "unknown", rationale: "The note is an inference and needs corroboration before it can substantively support a hypothesis." },
      H2: { verdict: "unknown", rationale: "The note does not identify a role or relationship with sufficient reliability." },
      H3: { verdict: "supports", rationale: "Without corroboration, the observation may be incidental to the other records." },
    },
  },
];

export const initialAssistantMessages: AssistantMessage[] = [
  {
    id: "assistant-welcome",
    role: "assistant",
    text: "I can help organize synthetic case context, surface cited records, and prepare graph actions for investigator review. I do not make findings of guilt or identity.",
    timestamp: "2026-08-30T17:46:00+05:30",
    citations: ["CASE-104", "Evidence-first mode"],
  },
];
